# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Smart Hub
email: contact@asmarthub.com
number: +33 6 10 26 40 19
description: |
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "http://smarthub.fr"

# Build settings
markdown:    kramdown
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

sass:
  sass_dir: _sass/
  style: compressed

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - gulpfile.js
  - package.json
  - node_modules/
  - README.md

keep_files:   [".git", ".svn", ".gitignore"]

# Markdown Processors
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1